services:

    Saldanhakun\TablerBundle\:
        resource: '../src'
        exclude:
            - '../src/{Entity,DependencyInjection,TablerBundle.php}'
        autowire: true

    Saldanhakun\TablerBundle\Twig\RuntimeExtension:
        class: Saldanhakun\TablerBundle\Twig\RuntimeExtension
        arguments:
            - '@event_dispatcher'
            - '@tabler_bundle.context_helper'
            - '%tabler_bundle.routes%'
            - '%tabler_bundle.icons%'
            - '%tabler_bundle.options%'
        tags:
            - { name: twig.runtime }

    Saldanhakun\TablerBundle\Twig\TablerExtension:
        class: Saldanhakun\TablerBundle\Twig\TablerExtension
        tags:
            - { name: twig.extension }
    Saldanhakun\TablerBundle\Form\Extension\CheckboxCustomizer:
        class: Saldanhakun\TablerBundle\Form\Extension\CheckboxCustomizer
        tags:
            - { name: form.type_extension }

    tabler_bundle.context_helper:
        class: Saldanhakun\TablerBundle\Helper\ContextHelper
        arguments:
            - '%tabler_bundle.options%'

    Saldanhakun\TablerBundle\Helper\ContextHelper:
        alias: tabler_bundle.context_helper

    Saldanhakun\TablerBundle\Security\EmailVerifier:
        class: Saldanhakun\TablerBundle\Security\EmailVerifier
        autowire: true

    Saldanhakun\TablerBundle\EventSubscriber\:
        resource: '../src/EventSubscriber/'
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    Saldanhakun\TablerBundle\Repository\UserRepository:
        class: Saldanhakun\TablerBundle\Repository\UserRepository
        tags:
            - { name: doctrine.repository_service }
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
